function winlagdata = euInfo_doTimeAndLagAnalysis( ...
  ftdata_dest, ftdata_src, winlagparams, flags, ...
  analysis_preproc, analysis_func, analysis_params, ...
  filter_preproc, filter_func, filter_params )

euUtil_warnDeprecated( 'Call eiCalc_doTimeAndLagAnalysis().' );

winlagdata = eiCalc_doTimeAndLagAnalysis( ...
  ftdata_dest, ftdata_src, winlagparams, flags, ...
  analysis_preproc, analysis_func, analysis_params, ...
  filter_preproc, filter_func, filter_params );

%
% This is the end of the file.
